### ISSUE TITLE
No issues, only thanks!

### ISSUE THREAD

**Issue by zymase** [stamparm/ipsum#1]
I happen to (still?) be a Windows user and I happened to discover this excellent _ipsum_ inadvertently in fact from https://github.com/AdguardTeam/AdguardDNS/issues/154 (I use Adguard filters with uBlockOrigin).

I most appreciate and download every morning when updating several blockers one of the available lists, master/levels/2.txt is my choice.

I don't use this list as primarily intended; rather I download it from
https://cdn.rawgit.com/stamparm/ipsum/master/levels/2.txt

and combine it with other address lists to make/update the address blacklist file to be used for DNSCrypt-Proxy.

What I most appreciate is this division into levels, a mighty clever and so handy approach for users.
I've chosen Level 2 because,
1- I like the idea "spotted once let it go, twice (or more!) block it! ;
2- Addresses spotted once only represent something like 75-80% of the complete list, too heavy in proportion of the risk

Many thanks, @stamparm , I repeat how I most appreciate your work. Daily updated lists moreover, what a worthy contribution to security.

**Comment by stamparm** [comment]
@zymase glad that you like it. "Level" idea you mentioned is basically the most important concept part here. I hope that at some point other users will discover that too :)
