### ISSUE TITLE
Invalid IP address

### ISSUE THREAD

**Issue by IgorMilavec** [stamparm/ipsum#11]
Today's feed contains an invalid IP address: 14.3.339.0
Otherwise: great resource, thank you!

**Comment by stamparm** [comment]
Hi.

Thank you for reporting. Added a filtering rule for the next update, so those kind of addresses should not be included in the future.

Cheers

**Comment by stamparm** [comment]
Reverted back the ".0" checking mechanism. It appears that those are indeed valid IPs.

Some examples:

A) **http://52.25.92.0/**

![1](https://user-images.githubusercontent.com/921555/102065558-0251d300-3df9-11eb-849f-956443c1027d.png)

---

B) **14.11.128.0**

![2](https://user-images.githubusercontent.com/921555/102065607-139adf80-3df9-11eb-81b2-dc921b35717d.png)

---

C) **45.83.64.0**

![3](https://user-images.githubusercontent.com/921555/102065805-50ff6d00-3df9-11eb-8c24-70ccdaca0e91.png)

---

D) **153.250.171.0**

![5](https://user-images.githubusercontent.com/921555/102066140-c10df300-3df9-11eb-9669-321d82592fd4.png)

---

p.s. https://stackoverflow.com/questions/14915188/ip-address-ending-with-zero

![6](https://user-images.githubusercontent.com/921555/102066352-029e9e00-3dfa-11eb-8748-73b88c8668eb.png)
