### ISSUE TITLE
Ip listed due to TCP reflection using spoofed IPs

### ISSUE THREAD

**Issue by mpfau** [stamparm/ipsum#13]
One of our ips has been listed due to TCP reflection attacks using our spoofed IPs (e.g. 81.3.6.164)

This has already happened in the past (see https://github.com/firehol/firehol/issues/437#issuecomment-678143417).

What is the process to get removed and whitelisted?

**Comment by stamparm** [comment]
Hi @mpfau 

Added it to whitelist and updated the ipsum accordingly

Best regards
