### ISSUE TITLE
invalid ip

### ISSUE THREAD

**Issue by alirezarayej** [stamparm/ipsum#14]
you have an invalid ip in ipsum.txt this ip is 181.215.223.911.

**Comment by alirezarayej** [comment]
also you can use [this](https://gist.github.com/alirezarayej/5b635d07607e64f12857c6e06ab8eee1) script to validate IPs.

**Comment by stamparm** [comment]
Hi.

Thank you for your report. Now going through the list and can't find any problems whatsoever.

Anyhow, included additional checks to prevent this kind of behavior in the future.

BR
