### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dhaavi** [stamparm/ipsum#15]
I came across this project and would like to use it as a data source in our open source project, the Portmaster: https://github.com/safing/portmaster.

To supply users with the lists, we collect them and send incremental updates - for that we'd need some kind of license that allows usage and redistribution. Have you considered adding a license to clear things up?

**Comment by stamparm** [comment]
Added this moment [The Unlicense](https://unlicense.org/). It is clearly the public domain, so you can do whatever you want with the data from IPsum

**Comment by dhaavi** [comment]
Great! Thanks for the fast response.
