### ISSUE TITLE
Can I have the Adguard version bad IPs list? thx

### ISSUE THREAD

**Issue by c2xusnpq6** [stamparm/ipsum#18]
You only need to add `$network` at the end ^^''
like this: `1.1.1.1` --> `1.1.1.1$network`

How to create your own ad filters | AdGuard Knowledgebase:
https://kb.adguard.com/zh/general/how-to-create-your-own-ad-filters#network-modifier

thx ^^

Adguard got a router version, windows software version and browser version BTW~
and I think it will very be useful for Ad blocker user to ban those bad IPs ^^

**Comment by stamparm** [comment]
1) `ipsum.txt` is as dumb as it gets. You can modify it to whatever form you need
2) IMO `ipsum` is not meant to be used as `Adguard` list. Those IPs are causing more problems as active attackers from the outside, than serving some ads/pua or similar
