### ISSUE TITLE
Is there a more detailed description of the meaning of the number field

### ISSUE THREAD

**Issue by hzbd** [stamparm/ipsum#21]
Hi, @stamparm 

Great project, thanks for sharing.

Are there any specific explanations for the meaning of the numbers in this column?

`https://github.com/stamparm/ipsum/blob/master/ipsum.txt`

![image](https://user-images.githubusercontent.com/3000843/124058832-b39a1c80-da5c-11eb-89d9-4d9a41d63908.png)

**Comment by stamparm** [comment]
for each IP, number of blacklists is exactly what is says: the number of tracked blacklists where the IP has been found in the last 24h period

**Comment by stamparm** [comment]
higher the number, more problematic/malicious the IP address is
