### ISSUE TITLE
levels/3.txt 404

### ISSUE THREAD

**Issue by Hcf1-vin** [stamparm/ipsum#22]
Hey @stamparm,

This is a really useful project. Thank you.

I've been using levels/3.txt but since the last commit its gone. Is this intentional?

`
curl https://raw.githubusercontent.com/stamparm/ipsum/master/levels/3.txt       
404: Not Found
`

**Comment by stamparm** [comment]
no worries, it has been a temporary "down", as Github changed some authentication stuff (github token required in the scripting). should be up and well from now on

**Comment by Hcf1-vin** [comment]
Thank you for your quick response. I'll keep an eye our tomorrow
