### ISSUE TITLE
Ipsum Daily feed of bad IPs Level 2 blocking Wikimedia Foundation Inc.

### ISSUE THREAD

**Issue by Cade66** [stamparm/ipsum#26]
Hi,
_Ipsum Daily feed of bad IPs **Level 2**_ is blocking `91.198.174.192` (Wikimedia Foundation Inc.).

**Comment by stamparm** [comment]
Hi.

Not sure what is going on, but that same IP is reported multiple times (e.g. https://www.abuseipdb.com/check/91.198.174.192). Nonetheless, I'll put it on a whitelist, so, with next automatic update (in 14h or so) it should be gone from ipsum.

Best regards

**Comment by Cade66** [comment]
Hi,

> Not sure what is going on, but that same IP is reported multiple times

Indeed. Odd. Thanks for acknowledging so quickly and whitelisting accordingly.

Best regards,
