### ISSUE TITLE
unlist personal IP from ipsum

### ISSUE THREAD

**Issue by TheRealOne78** [stamparm/ipsum#27]
Last week I installed a TOR relay for the reason of making the internet more anonymous and safe.
My ISP was contacted from the servers that were spammed by the relay users, and called me. 
Perhaps I removed the tor relay from my systems and will no longer cause any problems, because I don't wish to have problems and to make the internet a spamming area.

**Comment by stamparm** [comment]
ok. and what's the issue request here?

**Comment by stamparm** [comment]
ok. checked the "claim" and it really seems that you've run Tor node for not long. also, there were some "abuseip" complaints, but only in that time period (last 1 month). removed your IP address from ipsum and put it on my whitelist (it shouldn't be included in future updates)

**Comment by TheRealOne78** [comment]
thank you, I much appreciate it
