### ISSUE TITLE
not even an IPv6 in the list?

### ISSUE THREAD

**Issue by oantonioo** [stamparm/ipsum#31]
Are you assuming that the only malicious IPs are IPv4?
It's hard for me to believe that.

Or maybe you have an ipsumV6? I have not found it, if so I would like to use it.

Thank you

**Comment by stamparm** [comment]
Blacklists used do not contain IPv6 addresses. It is not like IPsum is making addresses up. Current trend in the blacklisting world are IPv4 addresses, at least to those relevant used in IPsum
