### ISSUE TITLE
ufw usage

### ISSUE THREAD

**Issue by mewcrazy** [stamparm/ipsum#32]
Hi,

I'd love to use your banlist in my setup. I'm already using the "ufw-bots" banlist with ufw: https://github.com/brahma-dev/ufw-bots

I'm quite new to Linus. Is it safe to additionally use yours with iptables?  I'd rather not want to lose all my existing ufw rules.

- Dennis

**Comment by stamparm** [comment]
AFAICS, `ufw` can be used in parallel with `iptables`/`ipset`, BUT... you have an option to use `ipset`/`iptables` in `ufw-bots` too (see: https://github.com/brahma-dev/ufw-bots/blob/master/files/iptables.sh), which would be even more "safe"

anyhow, `ufw` is a frontend to `iptables` (see: https://wiki.ubuntu.com/UncomplicatedFirewall). thus, there should be no problems in either case
