### ISSUE TITLE
removal request

### ISSUE THREAD

**Issue by GogetaSSJ666** [stamparm/ipsum#33]
Hi,

Can you delist this IP 94.199.178.9 from level 1?

**Comment by stamparm** [comment]
some background information? i can see it listed on https://www.abuseipdb.com/check/94.199.178.9. also, ipsum just uses 3rd party blacklists, so, there should be a good reason (if not a private IP) to remove it manually here

**Comment by GogetaSSJ666** [comment]
That was almost two years ago, and we have since fixed this bug.

Old Reports: The most recent abuse report for this IP address is from 1 year ago. It is possible that this IP is no longer involved in abusive activities.

**Comment by stamparm** [comment]
added to the local whitelist. next update (in cca. 3.5h) should remove that same IP

**Comment by GogetaSSJ666** [comment]
thanks
