### ISSUE TITLE
Updates more often?!

### ISSUE THREAD

**Issue by iJorgen** [stamparm/ipsum#34]
This is probably the best free collection of TI-feeds and smart with the "levels" to minimize false positives, but would it be possible to get updates more often than once a day? Blacklists for privacy is quite static and enough once a day, but cyber-threats needs faster response times. Maybe an update-rate of 3-6 hours (4-8 times per day). Would also get rid of any false-positives quicker.

Just a suggestion to make it even more effective... :-)

**Comment by stamparm** [comment]
based on experience, blacklist feeds are not updated in real-time. that being said, rare (free access) feeds will be updated more than once a day. IMHO once a day is pretty enough (<- also, based on experience :)
