### ISSUE TITLE
Should we continue to trust this list?

### ISSUE THREAD

**Issue by oantonioo** [stamparm/ipsum#42]
We have gone from having several million IPs to a few hundred thousand and suddenly to just over 10 thousand.

It's not a complaint, it's just a question.
Should we continue to trust this list?

Years ago this list even blocked spam mail, every day it recorded some blocking.
It's been a long time since it only blocks a couple of IPs every month.

thank you

**Comment by stamparm** [comment]
1) list hasn't been updated for last 7-10 days (until yesterday). there have been some authentication issues
2) feeds used from https://github.com/stamparm/maltrail/tree/master/trails/feeds are still alive and well. if you have some other list/feed to share, ready to be downloaded and parsed, please do and i'll include it too
3) my best indicator that `ipsum` is alive and well is the "wall of shame" that can be found at the front page (https://github.com/stamparm/ipsum). in case of any discrepancies or deviation between feeds/IP blacklists, there would be no "high score" IP addresses (e.g. >=8 lists scores)
4) you are always free to ditch ipsum and find something better

**Comment by oantonioo** [comment]
I don't know if I can find something better, but I'm sure they'll be more respectful.I told you about a very important problem that you were having, I did not try to offend you, a problem that you have decided to ignore.Yes, it's been a while since I got rid of IPsum and I thank you for these last years, now I trust ip.blackhole.monster that I don't know if it will be a worse list than yours, but at least it doesn't seem dead.
________________________________
De: Miroslav Stampar ***@***.***>
Enviado: sábado, 19 de agosto de 2023 9:37
Para: stamparm/ipsum ***@***.***>
Cc: oantonioo ***@***.***>; Author ***@***.***>
Asunto: Re: [stamparm/ipsum] Should we continue to trust this list? (Issue #42)


  1.  list hasn't been updated for last 7-10 days (until yesterday). there have been some authentication issues
  2.  feeds used from https://github.com/stamparm/maltrail/tree/master/trails/feeds are still alive and well. if you have some other list/feed to share, ready to be downloaded and parsed, please do and i'll include it too
  3.  my best indicator that ipsum is alive and well is the "wall of shame" that can be found at the front page (https://github.com/stamparm/ipsum). in case of any discrepancies or deviation between feeds/IP blacklists, there would be no "high score" IP addresses (e.g. >=8 lists scores)
  4.  you are always free to ditch ipsum and find something better

**Comment by stamparm** [comment]
@oantonioo please be more **thoughtful** and **smarter** next time. `ip.blackhole.monster` is just one of lists used in ipsum. if you've spent more than 1 minutes on researching https://github.com/stamparm/maltrail/tree/master/trails/feeds (which i provided in previous message), you could have find that
