### ISSUE TITLE
ipsum.txt list is broken

### ISSUE THREAD

**Issue by HolgerHees** [stamparm/ipsum#43]
Looks like the upload process is broken, because the list ends in the middle of an IP in Line 1248.

**Comment by patrick-7-7-7** [comment]
I have changed the commands in my script to get the IP list to 

IPSUM_URL_BLACKLIST=https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt

curl --compressed "$IPSUM_URL_BLACKLIST" 2>/dev/null | awk '$0 !~ /#/ && $2 && $2 >= 3 {print $1}'

**Comment by orzel** [comment]
I can confirm, the broken file breaks my import script.

**Comment by stamparm** [comment]
disk was full at that time. redoing everything ATM

**Comment by stamparm** [comment]
looks good now
