### ISSUE TITLE
Adding New version of ipsum.txt

### ISSUE THREAD

**Issue by HokairSupport** [stamparm/ipsum#44]
I have a list of bad IP addresses. They have tried to access or attack my systems. I am copying them manually and pasting them into the GitHub repository that I shared in the link below. The repository contains more than 12,000 IP addresses. When I compared it with your records, I found that 10,610 of them were the same. Is it possible to have a new file without the score numbers that you added? I want to use it as an external feed in the firewall because any additions to the IP addresses would render them invalid.
https://raw.githubusercontent.com/HokairSupport/ListOFIPAddresses/main/BlockIPAddresses.txt

**Comment by stamparm** [comment]
sorry, but i can't add random unverified IP addresses here. you can always combine ipsum and your address list by yourself (and use it)
