### ISSUE TITLE
This IP address (82.102.21.134) attacked my server and deployed mining software at 12:16:25 on November 29, 2023, Beijing time today.

### ISSUE THREAD

**Issue by PigeBest** [stamparm/ipsum#47]
Virus name: Linux.Risktool.Bitcoinminer.Ztjl
filename：xmrig
md5:7c631fca21e348ae4c3408ddd400b416

**Comment by stamparm** [comment]
this (ipsum) list is not meant for manually reporting IP addresses. it is just an aggregate. you should use specialized web pages, such as https://www.abuseipdb.com/
