### ISSUE TITLE
Feedback. Works with CSF. 

### ISSUE THREAD

**Issue by plutocrat** [stamparm/ipsum#5]
Just need to put an entry in csf.blocklist eg. 
IPSUM|86400|0|https://raw.githubusercontent.com/stamparm/ipsum/master/levels/8.txt

Explanation
Name=IPSUM
Refresh=1 day
Limit to number of IPS = disabled
URL = https://raw.githubusercontent.com/stamparm/ipsum/master/levels/8.txt

Check with csf -ra, then iptables -L -n

**Comment by stamparm** [comment]
Thank you. It will stay here for future reference
