### ISSUE TITLE
integrate with mikrotik

### ISSUE THREAD

**Issue by NazgulCoder** [stamparm/ipsum#52]
Hello, can i add this to my Mikrotik IP Firewall list that I daily update?

Thanks :)

**Comment by stamparm** [comment]
it can be used for sure. though, i don't know what functionality Mikrotik provides to do it

**Comment by stamparm** [comment]
license is [this](https://unlicense.org/):
![image](https://github.com/stamparm/ipsum/assets/921555/37b8e8d1-5a61-4df1-bef3-1c87b350acdd)

it means that you can do whatever you want with it
