### ISSUE TITLE
Commit history

### ISSUE THREAD

**Issue by randommen96** [stamparm/ipsum#53]
Hi,

I noticed that the commit history is wiped everytime a new commit is pushed to master,
this disables the abillity to review changes in the past, causing possible issues.

Would it be possible to keep the commit history instead of rewriting it everytime?

**Comment by stamparm** [comment]
nope, because it would result with huge commit history. already tried

**Comment by randommen96** [comment]
Out of curiosity, what kind of issues did you experience with a huge commit history?

**Comment by stamparm** [comment]
https://github.com/stamparm/ipsum/issues/6

Basically, git history grew at such pace, that after some time (AFAIR, it was after couple of weeks or smth) I had to switch to Git LFS. Then, quickly, quota would be used quickly by all the pulls.

![image](https://github.com/stamparm/ipsum/assets/921555/6a318dc5-ed74-41fb-b836-1562f835df42)

![image](https://github.com/stamparm/ipsum/assets/921555/a726f22f-22e9-44e5-bcd4-ca0c9b29fdf7)

**Comment by stamparm** [comment]
I hope that you all realize that the IP list changes are dramatic at each update (filling the Git history). It is not like programming couple of lines and code and pushing the changes

**Comment by randommen96** [comment]
I understand! 

So the git history grew outrageous in a short period of time.

Makes me wonder, would squashing the commits once in a while be a solution? It would take some scripting in the automated pushing, but I think it can work?
