### ISSUE TITLE
No more updates

### ISSUE THREAD

**Issue by QueenGit** [stamparm/ipsum#56]
Hey there.
There are no more updates of the ban lists since 6 days.
Is the project still supported or is it dead ?

Greetings

**Comment by stamparm** [comment]
sorry, my machine was down (for some reason) which did this in an automatic manner. fixed now. everything went back to normal

**Comment by knarfd** [comment]
Seems machine is down again :-) As no update has occured the last 5 days. Just a reminder here ;)

**Comment by stamparm** [comment]
@knarfd thx. i've triggered a manual update now, but seems that that same machine is failing hard. will take a look on Monday what's up

**Comment by knarfd** [comment]
Thank you, and also thanks for your work!

> @knarfd thx. i've triggered a manual update now, but seems that that same machine is failing hard. will take a look on Monday what's up
