### ISSUE TITLE
This list is blocking legitimate Bing Bot

### ISSUE THREAD

**Issue by saschaende** [stamparm/ipsum#58]
I integrated this list some minutes ago and just had some blocked ip adresses. I checked them.

For example: 

40.77.167.254 (1 Blocklist)
207.46.13.14 (2 Blocklists)
40.77.167.79 (1 Blocklist)

(+ 41 more ip adresses by other search engines like google, baidu, yandex.... since the last 24 hours)

User Agent of both:
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36

According to this: https://www.bing.com/toolbox/verify-bingbot

I checked both Ip Adresses and --> It's the Bing Bot.

So with this list I am blocking legitimate search angines? How can this happen?

**Comment by saschaende** [comment]
Lösung für PHP.

Wenn es eine Detection gab...

```
        // Array mit erlaubten Hostnamen
        $allowedHostnames = [
            'search.msn.com',
            'googlebot.com',
            'crawl.yahoo.net',
            // weitere Hostnamen hinzufügen
        ];

            // Führe den Reverse DNS Lookup durch
            $hostname = gethostbyaddr($request->ip());

            // Überprüfe, ob der Hostname in der Liste der erlaubten Hostnamen enthalten ist
            $hostnameAllowed = false;
            foreach ($allowedHostnames as $allowedHostname) {
                if (preg_match('/\.' . preg_quote($allowedHostname, '/') . '$/', $hostname)) {
                    $hostnameAllowed = true;
                    break;
                }
            }
```

**Comment by stamparm** [comment]
Those are appearing on couple of blacklists. I am not the author of those lists, where ipsum just **aggregates**. Furthermore, you are encouraged to use higher level lists (e.g. 4.txt or similar) as stated in README, to reduce the this kind of occurrences. 

Why is this happening? Maybe because blacklist providers don't like nosy bots?
