### ISSUE TITLE
Blocklist without occurance number?

### ISSUE THREAD

**Issue by hl2guide** [stamparm/ipsum#7]
An optional list without occurrence counts "total number of (black)list occurrence (for each)" would be really useful for usage in a DNS Sinkhole Server.

Please consider it 😸

**Comment by stamparm** [comment]
1) You haven't read the README which explains the concept of lists in levels directory. They are made just for this kind of requests
2) ipsum is more for ingress filtering than for egress (e.g. DNS) filtering as IPs on blacklists are usually detected by sensors

**Comment by hl2guide** [comment]
ok thanks for clarifying this 💃
